
src = 'patchloader.cc'

srcfiles = [('src/' + x) for x in Split(src)]

pl = Environment(CPPPATH = ['../libs/libppf', '../libs/libpdl',
                            '../libs/libnmpatch', '../libs/libnmprotocol'],
                 LIBPATH = ['/lib', '/usr/lib', '/usr/local/lib',
                            '../libs/libppf', '../libs/libpdl',
                            '../libs/libnmpatch', '../libs/libnmprotocol'],
                 LIBS = ['nmprotocol', 'nmpatch', 'pdl', 'ppf'])

opts = Options('patchloader.conf')
opts.Add(PathOption('PREFIX',
                    'Install dir (Defult: /usr/local)',
                    '/usr/local')) 
opts.Update(pl) 
opts.Save('patchloader.conf', pl)

conf = Configure(pl)

conf.env.Append(CPPFLAGS='-DVERSION=\'"0.1"\'')

if not conf.CheckLib('ppf'):
   print "libppf missing!"
   Exit(1);

if not conf.CheckLib('pdl'):
   print "libpdl missing!"
   Exit(1);

if not conf.CheckLib('nmpatch'):
   print "libnmpatch missing!"
   Exit(1);

if not conf.CheckLib('nmprotocol'):
   print "libnmprotocol missing!"
   Exit(1);

pl = conf.Finish()

idir_prefix = '$PREFIX'
idir_bin    = '$PREFIX/bin'

prog = pl.Program('patchloader', srcfiles)

pl.Install(idir_bin, prog)
pl.Alias('install', idir_prefix)

